"""NIYAM Strict Policy & Request Schemas
Pydantic v2 data contracts enforcing bounds, gate parameters, and decision outputs.
"""
from enum import Enum
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field, field_validator
from datetime import datetime, timezone


class ReasonCode(str, Enum):
    """Normalized deterministic reason codes for audit and reporting."""
    APPROVED = "APPROVED"
    PER_TRANSACTION_LIMIT_EXCEEDED = "PER_TRANSACTION_LIMIT_EXCEEDED"
    MONTHLY_CAP_EXCEEDED = "MONTHLY_CAP_EXCEEDED"
    CATEGORY_FORBIDDEN = "CATEGORY_FORBIDDEN"
    CATEGORY_CAP_EXCEEDED = "CATEGORY_CAP_EXCEEDED"
    CATEGORY_NOT_WHITELISTED = "CATEGORY_NOT_WHITELISTED"
    TIME_WINDOW_CLOSED = "TIME_WINDOW_CLOSED"
    NON_RETURNABLE_ITEM = "NON_RETURNABLE_ITEM"
    COD_NOT_ALLOWED = "COD_NOT_ALLOWED"
    DUPLICATE_SUPPRESSED = "DUPLICATE_SUPPRESSED"
    RAZORPAY_UNAVAILABLE = "RAZORPAY_UNAVAILABLE"
    SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR"
    AGENT_UNAUTHORIZED = "AGENT_UNAUTHORIZED"
    MERCHANT_BLOCKED = "MERCHANT_BLOCKED"
    WAIVER_APPLIED = "WAIVER_APPLIED"


class Limits(BaseModel):
    """Spending limits in INR."""
    max_per_transaction: float = Field(..., ge=0, description="Max spend per transaction (INR)")
    monthly_cap: float = Field(..., ge=0, description="Max cumulative spend in rolling 30 days (INR)")
    category_caps: Dict[str, float] = Field(
        default_factory=dict,
        description="Caps per category. 0 strictly forbids the category."
    )


class Constraints(BaseModel):
    """Product and operational constraints."""
    returnable_only: bool = Field(default=False, description="Require items to be returnable")
    cod_allowed_above: Optional[float] = Field(default=None, description="Threshold above which COD is allowed")
    allowed_categories: List[str] = Field(default_factory=list, description="Whitelist of allowed categories")
    blocked_merchants: List[str] = Field(default_factory=list, description="Blacklist of merchants/sellers")


class TimeWindow(BaseModel):
    """Active transaction time bounds."""
    active_hours: Optional[str] = Field(
        default=None,
        pattern=r"^([0-1][0-9]|2[0-3]):[0-5][0-9]-([0-1][0-9]|2[0-3]):[0-5][0-9]$",
        description="Daily active window in HH:MM-HH:MM (24-hour format)"
    )
    timezone: str = Field(default="Asia/Kolkata", description="IANA timezone name")
    allowed_days: List[str] = Field(
        default_factory=lambda: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        description="Allowed days of week"
    )


class SpendingPolicy(BaseModel):
    """Complete versioned policy object."""
    policy_version: str = Field(..., pattern=r"^v[0-9]+$", description="Policy version e.g. v1, v2")
    user_id: str = Field(..., description="Principal/Account holder ID")
    limits: Limits
    constraints: Constraints = Field(default_factory=Constraints)
    time_window: Optional[TimeWindow] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    raw_prompt: Optional[str] = Field(default=None, description="Original natural language prompt")


class PurchaseItem(BaseModel):
    """Item specification in a purchase cart."""
    id: str
    title: str
    price: float = Field(..., ge=0)
    category: str
    quantity: int = Field(default=1, ge=1)
    returnable: bool = Field(default=True)
    cod_allowed: bool = Field(default=True)
    merchant_id: Optional[str] = None


class PurchaseRequest(BaseModel):
    """Autonomous agent purchase execution request."""
    agent_id: str = Field(..., description="Registered agent ID")
    user_id: str = Field(..., description="User on whose behalf agent acts")
    items: List[PurchaseItem] = Field(..., min_length=1)
    total_amount: Optional[float] = Field(default=None, description="Cart total. If omitted, computed from items.")
    idempotency_key: str = Field(..., min_length=8, description="Deduplication key generated by client")
    waiver_id: Optional[str] = Field(default=None, description="Optional approved 1-tap waiver ID for budget override")
    payment_method: str = Field(default="upi", description="Payment rail: upi, card, cod")
    request_timestamp: Optional[datetime] = Field(default_factory=lambda: datetime.now(timezone.utc))

    def get_calculated_total(self) -> float:
        return sum(item.price * item.quantity for item in self.items)


class UserSpendState(BaseModel):
    """Historical ledger state for cumulative limit checks."""
    user_id: str
    monthly_spend_accumulated: float = 0.0
    category_spend_accumulated: Dict[str, float] = Field(default_factory=dict)


class ItemEvaluation(BaseModel):
    """Itemized pass/fail breakdown."""
    product_id: str
    category: str
    price: float
    passed: bool
    reason: Optional[str] = None


class EvaluationResult(BaseModel):
    """Deterministic output emitted by the evaluator engine."""
    allowed: bool
    reason_code: ReasonCode
    rule_fired: Optional[str] = None
    threshold: Optional[Any] = None
    actual_value: Optional[Any] = None
    explainability: str
    item_evaluations: List[ItemEvaluation] = Field(default_factory=list)
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
